### ISSUE TITLE
Can't enter bootloader mode

### ISSUE THREAD

**Issue by sommerper** [GEIGEIGEIST/qmk-config-klor#3]
Sorry to bother you again with what is probably a trivial thing.
I'm not sure if this is a problem with the configuration or QMK itself.

For some reason I can't get the Pro Micro to enter bootloader mode so I can flash a new firmware.

When I press the reset button twice the MCU immediatly enters the QMK software and it doesn't stay in bootloader mode for 8 seconds while I try to flash.

So bassically I'm trying to come up with a way that doesn't require me to constantly remove the mcu from the board and put it in the avr flasher whenever I make changes to the firmware.

How I build the firmware:
```
qmk compile -kb klor -km geist --env target=production
```

How I flash the bootloader:
```
/home/xxx/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17/bin/avrdude "-C/home/xxx/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17/etc/
avrdude.conf" -v -patmega32u4 -cstk500v1 -P/dev/ttyACM0 -b19200 "-Uflash:w:/home/xxx/qmk/qmk_firmware/klor_geist_bootloader.hex:i" -U lfuse:w:0x5E:m -U 
hfuse:w:0xD9:m -U efuse:w:0xC3:m -U lock:w:0x3F:m

```

How I flash the firmware:
```
/home/xxx/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17/bin/avrdude "-C/home/xxx/.arduino15/packages/arduino/tools/avrdude/6.3.
0-arduino17/etc/avrdude.conf" -v -patmega32u4 -cstk500v1 -P/dev/ttyACM0 -b19200 "-Uflash:w:/home/xxx/qmk/qmk_firmware/klor_geist.hex:i" -U 
lfuse:w:0x5E:m -U hfuse:w:0xD9:m -U efuse:w:0xC3:m -U lock:w:0x3F:m
```

Now, when I plug in the USB cable and reset the MCU I would expect the MCU to show up as /dev/ttyACM0 or /dev/ttyACM1 - but it doesn't.

Could you perchance share your way to quickly itterate and test changes when updating the firmware?

Thanks again for a great keyboard!

**Comment by GEIGEIGEIST** [comment]
In my experience this happens with cheap Pro Micros (at least in my case this was kind of the reason). I got two cheap ones from AliExpress where this happens all the time. I used QMK toolbox to flash them and set it to Auto-Flash. This way it flashes your Pro Micro as soon as it goes into boot mode. In my case AVRDudess worked even better than toolbox.

**Comment by sommerper** [comment]
Sorry for the slow response time. If I flash it with the planck firmware it works but I don't know the differences between the two layouts well enough to say why it would work on one and not the other. I couldn't find a way to single out the issue.
Thanks anyway for trying to help.

**Comment by GEIGEIGEIST** [comment]
I'm sorry I couldn't help you on this.
